apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- if and .Values.iam .Values.iam.enabled (include "common.aws.oidcProvider" .) }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ include "common.aws.accountId" . }}:role/{{ .Values.appName }}-role
  {{- end }}
